
server:
  port: 8890
spring:
  application:
    name: SALES-ORDER
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud_sales?characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  jpa:
    show-sql: true

env: dev3
# 修改Ribbon负载均衡策略
#SALES-PRODUCT:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
girl:
  name: lyz
  age: 20
